"""empty message

Revision ID: 1455c55602c6
Revises: 60d530ea434d
Create Date: 2019-02-15 22:59:34.689424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1455c55602c6'
down_revision = '60d530ea434d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=64), nullable=True),
    sa.Column('lastName', sa.String(length=64), nullable=True),
    sa.Column('bannerID', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('gpa', sa.String(length=64), nullable=True),
    sa.Column('currentTotal', sa.String(length=64), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_firstName'), 'student', ['firstName'], unique=False)
    op.create_index(op.f('ix_student_lastName'), 'student', ['lastName'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_lastName'), table_name='student')
    op.drop_index(op.f('ix_student_firstName'), table_name='student')
    op.drop_table('student')
    # ### end Alembic commands ###
