"""empty message

Revision ID: 2c6891ccdb75
Revises: 1455c55602c6
Create Date: 2019-02-16 12:53:12.864180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c6891ccdb75'
down_revision = '1455c55602c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('creditTotal', sa.String(length=64), nullable=True))
    op.drop_column('student', 'currentTotal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('currentTotal', sa.VARCHAR(length=64), nullable=True))
    op.drop_column('student', 'creditTotal')
    # ### end Alembic commands ###
