"""empty message

Revision ID: 60d530ea434d
Revises: 181132729c66
Create Date: 2019-02-12 19:42:59.489317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60d530ea434d'
down_revision = '181132729c66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('faculty', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'faculty')
    # ### end Alembic commands ###
